[build]
  base = ""
  publish = "_site"
  command = "quarto render"

[context.production.environment]
  QUARTO_VERSION = "1.2.313"  # Use a valid Quarto version

[context.production]
  command = """
    # Install Quarto
    wget -O quarto.tar.gz https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.313/quarto-1.2.313-linux-amd64.tar.gz
    tar -xzf quarto.tar.gz -C /opt/
    export PATH=/opt/quarto-1.2.313/bin:$PATH
    
    # Render the site
    quarto render
  """
