---
title: "Publications"
---

See also:

-   [OrcID](https://orcid.org/0000-0001-7234-4804)
-   [Google Scholar Profile](https://scholar.google.com/citations?user=q1JFM00AAAAJ)

## Peer reviewed Publications 

1.   Gobena, M.G. and **Berelie, Y**., 2021. Modeling the Determinant of Time to Age at First Marriage among Women in Ethiopia using Cox models with mixed effects. [BMC Reproductive Health](https://reproductive-health-journal.biomedcentral.com/).volume 19, Article number: 32 (2022). [DOI link](https://doi.org/10.1186/s12978-022-01339)

2.  **Berelie, Y.,** Yeshiwas, D., Yismaw, L., Alene, M. (2020). Determinants of institutional delivery service utilization in Ethiopia: a population-based cross-sectional study. [BMC Public Health](https://bmcpublichealth.biomedcentral.com/), 20, 1077. [doi link](https://doi.org/10.1186/s12889-020-09125-2)

3.  Alene M, Yismaw L, **Berelie Y**, Kassie B, Yeshambel R, Assemie MA (2020). Prevalence and determinants of unintended pregnancy in Ethiopia: A systematic review and meta-analysis of observational studies. [PLoS ONE](https://journals.plos.org/plosone/) 15(4): e0231012. [doi link](https://doi.org/10.1371/journal.pone.0231012).

4.  Yeshiwas, D., & **Berelie, Y.** (2020). Forecasting the Covolatility of Coffee Arabica and Crude Oil Prices: A Multivariate GARCH Approach with High-Frequency Data. [Journal of Probability and Statistics](https://onlinelibrary.wiley.com/journal/5139) 2020(2):1-10. [Doi link](https://doi.org/10.1155/2020/1424020).

5.  **Berelie, Y.,** Yismaw, L., Tesfa, E., & Alene, M. (2019). Risk factors for under-five mortality in Ethiopia: Evidence from the 2016 Ethiopian Demographic and Health Survey. [South African Journal of Child Health](http://www.sajch.org.za/index.php/SAJCH), 13(3), 137-140. [DOI link](https://doi.org/10.7196/SAJCH.2019.v13i3.1645).

6.  Alene, M., Yismaw, L., **Berelie, Y**., & Kassie, B. (2019). Health care utilization for common childhood illnesses in rural parts of Ethiopia: evidence from the 2016 Ethiopian demographic and health survey. [BMC Public Health](https://bmcpublichealth.biomedcentral.com/), 19(1), 57. [Doi link](https://doi.org/10.1186/s12889-019-6397-x)

## Manuscripts under review

2.	Berelie Y., Jim Todd, Robert Peck, 2024. A mixed model for assessing the impact of DTG-based ART regime on weight change in Tanzanian HIV patients. (Submitted to International AIDS).
3.	Mulusew J., Saba Y, Fikreselassie G. , Yebelay B. , et al., 2024. Maternal education and child vaccination in Ethiopia: A natural experiment. Elsevier, journal of Social Science & Medicine.

## Under preparation 

1.	Prevalence of zero-dose children and factors associated before and after COVID-19 among children aged 12–23 months across 8 African countries.
2.	Sisay Alemayehu Abayneh, Yebelay Berelie, Biniyam Eskinder Seid, Dereje Habte, Wondimu Teferi, Minesh Shah Pradyuman. Time to Viral Suppression after documented Virologic failure in Addis Ababa, Ethiopia.


## Seminar presentation:

1.  Difference-in-Differences (DID) for Impact Evaluation, October 25, 2021, Stellenbosch University, South Africa.
2.  Insight to Different Methods for Handling Missing Data: Application with R, July 5, 2021, Debre Markos University, Ethiopia.
